### ISSUE TITLE
Quick question about training time

### ISSUE THREAD

**Issue by greeneggsandyaml** [advimman/CIPS#1]
Hello authors,

Thank you for your paper -- it looks very interesting! I had a quick question about training time: how long (and with how many GPUs) does it take you to train the pretrained models provided in the repo? Do you find that the method is slow or fast relative to StyleGAN2? 

I look forward to playing around with the repo over the next week! 

Best,
greeneggsandyaml

**Comment by avecplezir** [comment]
Hi!

Thanks for the question. 
With our implementation, CIPSis 4.3x times slower than StyleGANv2 and has 3.3x moreMACs (at 256x resolution). We trained our model on eight P40  GPUs and showed approximately  3.2  mln images to the discriminator during training. It took about two weeks to get these checkpoints. 

Best wishes,
Ivan

**Comment by greeneggsandyaml** [comment]
Thank you for the response! I really appreciate it, and I'm closing the issue.
